name = "Swizzles"
uuid = "60694085-d904-4bfc-95dc-1e0e768e9359"
authors = ["Cédric BELMANT"]
version = "0.1.0"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[weakdeps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
SwizzlesStaticArraysExt = "StaticArrays"

[compat]
PrecompileTools = "1"
StaticArrays = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StaticArrays"]
