name = "Swizzles"
uuid = "60694085-d904-4bfc-95dc-1e0e768e9359"
authors = ["Cédric BELMANT"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
